Remove telemetry dependency
appsignal/appsignal-elixir-phoenix pull request #27
Opened 2021-08-13 10:36 UTC by luismiramirez

Telemetry dependency is not needed for this library as it is already a dependency of appsignal-elixir, which this library depends on through appsignal-plug.

2021-08-13 11:19 UTC, tombruijn commented
@luismiramirez I think a changeset would be good for this PR. It's a change users will notice (less conflicts with dependencies) and it's a change that we will release a new version of the package for if no other changes had a changeset.

When a PR is ready for review, please press the "ready for review" button. I marked it as such.

Please don't delete backlog helper comments. It will update it on its own after it detects changes, in this case it would have detected your edit of the PR body.

2021-08-13 11:20 UTC, tombruijn approved these changes

2021-08-13 11:20 UTC, tombruijn requested changes
Please add a changeset to the PR :)

2021-08-13 13:00 UTC, tombruijn approved these changes

2021-08-16 10:12 UTC, jeffkreeftmeijer approved these changes
Looks good. I’ve also checked to make sure the earliest appsignal-elixir version that’s allowed in this setup (which is 2.1.5) actually depends on Telemetry, which it does.

2021-08-16 11:25 UTC, merged