Resolve mime dependency issue for Elixir 1.9
appsignal/appsignal-elixir-phoenix pull request #29
Opened 2021-08-20 06:51 UTC by luismiramirez

Mime is depended on by plug in all environments. CI
breaks on Elixir 1.9.4 if it picks mime 2.0.x. This patch explicitly
locks to mime ~> 1.0 on Elixir versions before 1.10.

2021-08-20 08:42 UTC, thijsc approved these changes

2021-08-20 08:59 UTC, tombruijn requested changes

2021-08-20 08:59 UTC, tombruijn commented on .changesets/fix-mono-dependency-support-for-elixir-1-9.md
> +Fix mono dependency support for Elixir 1.9
No changeset needed here I think. See my other comment.
This change should not result in a change for the user.

2021-08-20 08:59 UTC, tombruijn commented on mix.exs
> +        :lt -> [{:mime, "~> 1.0"}]
```suggestion
        :lt -> [{:mime, "~> 1.0", only: [:test, :test_no_nif]}]
```

Mime is a transient dependency through plug, not a direct dependency. It's a dependency for which we only need to specify a specific version on older Elixir versions in the test environment.

If we were to publish the original change, the `appsignal_phoenix` package would have an additional dependency for mime dependending on what version of Elixir it was published from.

2021-08-23 09:54 UTC, luismiramirez commented
@tombruijn `plug` has `mime` as a non-test dependency, so the build in Semaphore failed. Apparently, we have to keep this conditional dependency on all environments.

2021-08-23 21:00 UTC, tombruijn commented
Yes it's a dependency in all environments, but I would think we don't need to specify it ourselves because it's an inherited dependency through the plug package.

We only need to specify which version in the test environment for certain environments. It will be resolved as normally in all the other Elixir version jobs.

2021-08-24 07:16 UTC, luismiramirez commented
Yes, it's specified for Elixir versions lower than 1.10 but if we add the: `only: [:test, :test_no_nif]` restriction as with the Elixir library, it fails on Semaphore with:

```
the :only option for dependency mime

  > In mix.exs:
    {:mime, "~> 1.0", [env: :prod, repo: "hexpm", hex: "mime", only: [:test, :test_no_nif]]}

  does not match the :only option calculated for

  > In deps/plug/mix.exs:
    {:mime, "~> 1.0 or ~> 2.0", [env: :prod, hex: "mime", repo: "hexpm", optional: false]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
export SEMAPHORE_JOB_RESULT=failed
```

2021-08-24 07:58 UTC, tombruijn commented
@luismiramirez ah it's because it's a dependency through plug that plug doesn't list as a test dependency. What I would do then is the following, only add the dependency when mix is loaded in the test env:

```diff
diff --git mix.exs mix.exs
index ddc93ff..bece673 100644
--- mix.exs
+++ mix.exs
@@ -45,9 +45,13 @@ defmodule Appsignal.Phoenix.MixProject do
     system_version = System.version()

     mime_dependency =
-      case Version.compare(system_version, "1.10.0") do
-        :lt -> [{:mime, "~> 1.0"}]
-        _ -> []
+      if Mix.env == :test || Mix.env == :test_no_nif do
+        case Version.compare(system_version, "1.10.0") do
+          :lt -> [{:mime, "~> 1.0"}]
+          _ -> []
+        end
+      else
+          []
       end
```

I really don't want to list it as a runtime dependency because then we also specify mime as a dependency of the appsignal packages directly.

2021-08-24 08:38 UTC, luismiramirez commented
@tombruijn That's a good one, thank you!

2021-09-08 12:33 UTC, tombruijn approved these changes

2021-09-09 11:58 UTC, merged