Support Phoenix 1.7's template telemetry
appsignal/appsignal-elixir-phoenix pull request #54
Opened 2022-11-23 12:26 UTC by jeffkreeftmeijer

Instead of using Appsignal.View, Appsignal.EventHandler subscribes to Phoenix 1.7's new template telemetry to gain template rendering insights.

2022-11-24 09:44 UTC, jeffkreeftmeijer commented
I’ll add docs (https://github.com/appsignal/appsignal-docs/issues/896) and a blogpost (https://github.com/appsignal/appsignal-nextjs-blog/issues/716), but this one’s ready for review.

2022-11-24 10:25 UTC, luismiramirez approved these changes

2022-11-24 10:39 UTC, tombruijn approved these changes

2022-11-25 07:56 UTC, jeffkreeftmeijer commented
Will merge and release this next week.

2022-11-30 11:45 UTC, unflxw requested changes
Looks good other than the event name and exception event handling as mentioned in the comment.

It would also be nice to report an exception if it happens, but it's not a requirement.

2022-12-06 10:42 UTC, merged

2022-12-06 11:31 UTC, jeffkreeftmeijer commented
AppSignal for Phoenix 2.2.0 was released, which includes this patch. Note that because template telemetry (https://github.com/phoenixframework/phoenix/commit/f095d1f82cdf18ffc69226fd59ce36a7fc2ffb44) hasn’t been released yet, you’ll need to depend on Phoenix from git to make this work as of right now.